package analysisSets;

public enum AnalysisType {
	TINA_BY_TRIAL, 
	EXTINCTION, 
	PROGRESSIVE_RATIO, 
	CPT_BASELINE, 
	FIVE_CHOICE,
	FIVE_CHOICE_RAT,
	PAIRWISE_DISCRIMINATION,
	OTAGO_PAIRWISE_DISCRIMINATION,
	TUNL,
	PAIRWISE_HABITUATION_V2,
	MPOSNER_PROBES
}
